import Head from "next/head";
import Header from "@/components/Header/Header";
import Toggle from "@/components/Toggle/Toggle";
import Footer from "@/components/Footer/Footer";
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { useState } from "react";
import { motion } from "framer-motion";
import { useEffect } from "react";
import { useRouter } from "next/router";
import { pageview } from "../lib/ga";

export default function App({ Component, pageProps, router }: AppProps) {
  const [darkMode, setdarkMode] = useState(true);
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  // Google Analytics
  useEffect(() => {
    const handleRouteChange = (url: any) => {
      pageview(url);
    };

    //When the component is mounted, subscribe to router changes
    //and log those page views
    router.events.on("routeChangeComplete", handleRouteChange);

    // If the component is unmounted, unsubscribe
    // from the event with the `off` method
    return () => {
      router.events.off("routeChangeComplete", handleRouteChange);
    };
  }, [router.events]);

  const handleMenuToggle = () => {
    setIsMenuOpen(!isMenuOpen);
  };
  return (
    <>
      {" "}
      <Head>
        <title>Khalil Merine Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={darkMode ? "dark " : ""}>
        <main className="bg-white px-5 md:px-20 dark:bg-gray-900">
          {isMenuOpen ? (
            <Toggle
              setIsMenuOpen={setIsMenuOpen}
              handleMenuToggle={handleMenuToggle}
            />
          ) : (
            ""
          )}
          <Header
            darkMode={darkMode}
            setdarkMode={setdarkMode}
            isMenuOpen={isMenuOpen}
            setIsMenuOpen={setIsMenuOpen}
            handleMenuToggle={handleMenuToggle}
          />

          <motion.div
            key={router.route}
            initial="pageInitial"
            animate="pageAnimate"
            variants={{
              pageInitial: {
                opacity: 0,
              },
              pageAnimate: {
                opacity: 1,
              },
            }}
          >
            <Component {...pageProps} />
          </motion.div>
          <Footer />
        </main>
      </div>
    </>
  );
}
